server:
  port: "8181"
spring:
  datasource:
    url: 'jdbc:postgresql://192.168.1.9:5432/khob_db'
    username: 'postgres'
    password: "0000"
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: 'update'
application:
  security:
    jwt:
      secret-key: '404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970'
      expiration: "86400000" #A day
      refresh-token:
        expiration: "604800000" #A week

jwt:
  cookieExpiry: "1800"
logging:
  level:
    org:
      springframework:
        security: "DEBUG"